apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: judge-cert
spec:
  secretName: judge-cert-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - judge.resamvi.io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
