apiVersion: v1
kind: ConfigMap
metadata:
  name: judge-server-config
  labels:
    app: judge-server
data:
  DATABASE_URL: julien:dbpassword@postgres.default.svc.cluster.local:5432/mydb?sslmode=disable
  ADMIN_PASSWORD: adminpassword
  ENV: production
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: judge-server
  name: judge-server
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: judge-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: judge-server
  name: judge-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge-server
  template:
    metadata:
      labels:
        app: judge-server
    spec:
      containers:
      - image: ghcr.io/resamvi/judge:latest
        name: judge-server
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: judge-server-config
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"